//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.16 at 12:22:29 PM BST 
//


package uk.gov.gsi.childmaintenance.futurescheme.bo.esb.deoschedule.cmecinquiredeodetailsresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CMECInquireDEODetailsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CMECInquireDEODetailsResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResponseHeader" type="{http://www.childmaintenance.gsi.gov.uk/futurescheme/bo/common/Response.xsd}Response" minOccurs="0"/>
 *         &lt;element name="InquireDEOResponse" type="{http://www.childmaintenance.gsi.gov.uk/futurescheme/bo/esb/deoSchedule/CMECInquireDEODetailsResponse}InquireDEOResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CMECInquireDEODetailsResponse", propOrder = {
    "responseHeader",
    "inquireDEOResponse"
})
public class CMECInquireDEODetailsResponse {

    @XmlElement(name = "ResponseHeader")
    protected Response responseHeader;
    @XmlElement(name = "InquireDEOResponse")
    protected InquireDEOResponse inquireDEOResponse;

    /**
     * Gets the value of the responseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponseHeader() {
        return responseHeader;
    }

    /**
     * Sets the value of the responseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponseHeader(Response value) {
        this.responseHeader = value;
    }

    /**
     * Gets the value of the inquireDEOResponse property.
     * 
     * @return
     *     possible object is
     *     {@link InquireDEOResponse }
     *     
     */
    public InquireDEOResponse getInquireDEOResponse() {
        return inquireDEOResponse;
    }

    /**
     * Sets the value of the inquireDEOResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link InquireDEOResponse }
     *     
     */
    public void setInquireDEOResponse(InquireDEOResponse value) {
        this.inquireDEOResponse = value;
    }

}
