//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.16 at 12:22:29 PM BST 
//


package uk.gov.gsi.childmaintenance.futurescheme.bo.esb.deoschedule.cmecinquiredeodetailsresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InquireDEOResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InquireDEOResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employerAccountId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="scheduleStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployerScheduleDetailsCollection" type="{http://www.childmaintenance.gsi.gov.uk/futurescheme/bo/esb/deoSchedule/CMECInquireDEODetailsResponse}EmployerScheduleDetailsCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InquireDEOResponse", propOrder = {
    "employerAccountId",
    "action",
    "fromDate",
    "toDate",
    "scheduleStatus",
    "employerScheduleDetailsCollection"
})
public class InquireDEOResponse {

    protected String employerAccountId;
    protected String action;
    protected String fromDate;
    protected String toDate;
    protected String scheduleStatus;
    @XmlElement(name = "EmployerScheduleDetailsCollection")
    protected EmployerScheduleDetailsCollection employerScheduleDetailsCollection;

    /**
     * Gets the value of the employerAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployerAccountId() {
        return employerAccountId;
    }

    /**
     * Sets the value of the employerAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployerAccountId(String value) {
        this.employerAccountId = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDate(String value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToDate(String value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the scheduleStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleStatus() {
        return scheduleStatus;
    }

    /**
     * Sets the value of the scheduleStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleStatus(String value) {
        this.scheduleStatus = value;
    }

    /**
     * Gets the value of the employerScheduleDetailsCollection property.
     * 
     * @return
     *     possible object is
     *     {@link EmployerScheduleDetailsCollection }
     *     
     */
    public EmployerScheduleDetailsCollection getEmployerScheduleDetailsCollection() {
        return employerScheduleDetailsCollection;
    }

    /**
     * Sets the value of the employerScheduleDetailsCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployerScheduleDetailsCollection }
     *     
     */
    public void setEmployerScheduleDetailsCollection(EmployerScheduleDetailsCollection value) {
        this.employerScheduleDetailsCollection = value;
    }

}
