//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.14 at 11:16:02 AM BST 
//

package uk.gov.gsi.childmaintenance.futurescheme.bo.esb.eportal.cmecgetclientdetailsrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CMECHeader complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CMECHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reqSystemName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originatorID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originatorIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sourceObjectId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="branchNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sensitiveAccessFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hostName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="autoCompleteFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CMECHeader", namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/bo/common/CMECHeader.xsd", propOrder = {
		"serviceName", "operation", "reqSystemName", "originatorID", "originatorIP", "sourceObjectId", "branchNumber",
		"seqNum", "timeStamp", "sensitiveAccessFlag", "hostName", "autoCompleteFlag" })
public class CMECHeader {

	protected String autoCompleteFlag;
	protected String branchNumber;
	protected String hostName;
	protected String operation;
	protected String originatorID;
	protected String originatorIP;
	protected String reqSystemName;
	protected String sensitiveAccessFlag;
	protected String seqNum;
	protected String serviceName;
	protected String sourceObjectId;
	protected String timeStamp;

	/**
	 * Gets the value of the autoCompleteFlag property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAutoCompleteFlag() {
		return autoCompleteFlag;
	}

	/**
	 * Gets the value of the branchNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBranchNumber() {
		return branchNumber;
	}

	/**
	 * Gets the value of the hostName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHostName() {
		return hostName;
	}

	/**
	 * Gets the value of the operation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOperation() {
		return operation;
	}

	/**
	 * Gets the value of the originatorID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOriginatorID() {
		return originatorID;
	}

	/**
	 * Gets the value of the originatorIP property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOriginatorIP() {
		return originatorIP;
	}

	/**
	 * Gets the value of the reqSystemName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReqSystemName() {
		return reqSystemName;
	}

	/**
	 * Gets the value of the sensitiveAccessFlag property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSensitiveAccessFlag() {
		return sensitiveAccessFlag;
	}

	/**
	 * Gets the value of the seqNum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSeqNum() {
		return seqNum;
	}

	/**
	 * Gets the value of the serviceName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getServiceName() {
		return serviceName;
	}

	/**
	 * Gets the value of the sourceObjectId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSourceObjectId() {
		return sourceObjectId;
	}

	/**
	 * Gets the value of the timeStamp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTimeStamp() {
		return timeStamp;
	}

	/**
	 * Sets the value of the autoCompleteFlag property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAutoCompleteFlag(String value) {
		this.autoCompleteFlag = value;
	}

	/**
	 * Sets the value of the branchNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBranchNumber(String value) {
		this.branchNumber = value;
	}

	/**
	 * Sets the value of the hostName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHostName(String value) {
		this.hostName = value;
	}

	/**
	 * Sets the value of the operation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOperation(String value) {
		this.operation = value;
	}

	/**
	 * Sets the value of the originatorID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOriginatorID(String value) {
		this.originatorID = value;
	}

	/**
	 * Sets the value of the originatorIP property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOriginatorIP(String value) {
		this.originatorIP = value;
	}

	/**
	 * Sets the value of the reqSystemName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReqSystemName(String value) {
		this.reqSystemName = value;
	}

	/**
	 * Sets the value of the sensitiveAccessFlag property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSensitiveAccessFlag(String value) {
		this.sensitiveAccessFlag = value;
	}

	/**
	 * Sets the value of the seqNum property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSeqNum(String value) {
		this.seqNum = value;
	}

	/**
	 * Sets the value of the serviceName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setServiceName(String value) {
		this.serviceName = value;
	}

	/**
	 * Sets the value of the sourceObjectId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSourceObjectId(String value) {
		this.sourceObjectId = value;
	}

	/**
	 * Sets the value of the timeStamp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTimeStamp(String value) {
		this.timeStamp = value;
	}

}
