//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.15 at 01:35:12 PM BST 
//

package uk.gov.gsi.childmaintenance.futurescheme.bo.esb.eportal.cmecgetclientdetailsrequest;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * uk.gov.gsi.childmaintenance.futurescheme.bo.esb.eportal.
 * cmecgetclientdetailsrequest package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * uk.gov.gsi.childmaintenance.futurescheme.bo.esb.eportal.
	 * cmecgetclientdetailsrequest
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link CmecEPortalAddress }
	 * 
	 */
	public CmecEPortalAddress createCmecEPortalAddress() {
		return new CmecEPortalAddress();
	}

	/**
	 * Create an instance of {@link CmecEPortalCaseContactDetails }
	 * 
	 */
	public CmecEPortalCaseContactDetails createCmecEPortalCaseContactDetails() {
		return new CmecEPortalCaseContactDetails();
	}

	/**
	 * Create an instance of {@link CmecEPortalContactDetails }
	 * 
	 */
	public CmecEPortalContactDetails createCmecEPortalContactDetails() {
		return new CmecEPortalContactDetails();
	}

	/**
	 * Create an instance of {@link CmecEPortalHLSCaseDetails }
	 * 
	 */
	public CmecEPortalHLSCaseDetails createCmecEPortalHLSCaseDetails() {
		return new CmecEPortalHLSCaseDetails();
	}

	/**
	 * Create an instance of {@link CmecGetClientDetailsResponse }
	 * 
	 */
	public CmecGetClientDetailsResponse createCmecGetClientDetailsResponse() {
		return new CmecGetClientDetailsResponse();
	}

	/**
	 * Create an instance of {@link Response }
	 * 
	 */
	public Response createResponse() {
		return new Response();
	}

	/**
	 * Create an instance of {@link Response.ResponseDetails }
	 * 
	 */
	public Response.ResponseDetails createResponseResponseDetails() {
		return new Response.ResponseDetails();
	}

}
