//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.09 at 03:57:43 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://github.com/deekumar18/soap_mock", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.deekumar18.soap_mock;
